name: adf_cuidapet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: 5.0.3
  mobx: 2.0.7+5
  flutter_mobx: 2.0.6+1
  asuka: 2.0.1+1
  dio: 4.0.6
  flutter_screenutil: 5.5.4
  firebase_core: 1.22.0
  firebase_auth: 
  firebase_remote_config:
  # firebase_remote_config: 2.0.17
  firebase_messaging: 13.0.1
  flutter_dotenv: 5.0.2
  logger: 1.1.0

  flutter_secure_storage: 5.0.2
  shared_preferences: 2.0.15
  validatorless: 1.2.1
  google_sign_in: 5.3.0
  flutter_facebook_auth: 4.3.0
  # flutter_facebook_auth: ^4.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.0.7
  build_runner: 2.2.0

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - .env
      #   - images/a_dot_ham.jpeg



  fonts:
    - family: Cuidapeticons
      fonts:
        - asset: assets/fonts/Cuidapeticons.ttf

